---
kind: Service
apiVersion: v1
metadata:
  name: axcoto
  namespace: opty
spec:
  selector:
    app: axcoto
  ports:
    - protocol: TCP
      port: 80
      name: web

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: axcoto-ingress
  namespace: opty
spec:
  tls: # specify domains to fetch certificates for
  - hosts:
    - axcoto.com
    - www.axcoto.com
  rules:
  - host: axcoto.com
    http:
      paths:
      - path: /
        pathType: "ImplementationSpecific"
        backend:
          service:
            name: axcoto
            port:
              name: web
