kind: Deployment
apiVersion: apps/v1
metadata:
  name: axcoto
  namespace: opty
  labels:
    app: axcoto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: axcoto
  template:
    metadata:
      labels:
        app: axcoto
        name: axcoto
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: axcoto/website:${GIT_COMMIT}
        name: axcoto
